# Dockerfile.frontend
FROM node:18

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos package.json y package-lock.json del frontend
COPY ./pokemon/package*.json ./

# Instalar las dependencias del frontend
RUN npm install

# Copiar el código fuente del frontend
COPY ./pokemon .

# Construir la aplicación frontend
RUN npm run build

# Servir la aplicación con un servidor estático o copiar los archivos a Nginx
EXPOSE 80

# Comando para servir el frontend
CMD ["npx", "http-server", "dist"]
